name: Ci
On:
    push:
        branches:
            main
jobs:
    build:
        runs-on: ubuntu-latest
        env:
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2


            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                distribution : 'adopt'
                java-version : '11'


            - name: Build with Maven
              run: mvn -B clean package


    test:
        runs-on: ubuntu-latest
        env:
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2


            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                distribution : 'adopt'
                java-version : '11'


            - name: Test with Maven
              run: mvn test


    deploy:
        runs-on: ubuntu-latest
        env:
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2


            - name: Set up Docker
              uses: docker/setup-docker@v2


            - name: Deploy with Docker Compose
              run: |
                           # Pull the Docker images from Docker Hub
                           docker-compose -f docker-compose.yml pull
                   
                           # Run the services using Docker Compose
                           docker-compose -f docker-compose.yml up -d


