name: CI idlhaj
On:
    push:
        branches:
            main
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            JAVA_HOME: "11"
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2


            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                distribution : 'adopt'
                java-version : '11'


            - name: Build with Maven
              run: mvn -B clean package


    test:
        runs-on: ubuntu-latest
        env:
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2


            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                distribution : 'adopt'
                java-version : '11'


            - name: Test with Maven
              run: mvn test


    deploy:
        runs-on: ubuntu-latest
        env:
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2


            - name: Build images and Push to Docker Hub
              run: |
                   	for ser in $dir/*; do
                   		if [ -d "$ser" ] && [ -e "$ser/Dockerfile" ]; then
                   			ser_name=$(basename "$ser")
                   			ser_name=${ser_name,,}
                   			docker build -t $ser_name:latest "$ser"
                   			docker tag $ser_name:latest ${{ secrets.DOCKERHUB_USERNAME }}/$ser_name:latest
                   			docker push ${{ secrets.DOCKERHUB_USERNAME }}/$ser_name:latest
                   		fi
                   	done
                                       
              with:
                dir : './'


